services:
  app:
    build: .
    container_name: pdfextractext-app-1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # Esto le dice a tu código de Python que la DB está en el host 'db'
      - MONGO_URL=mongodb://db:27017
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: pdfextractext-db-1
    # Este comando reduce drásticamente los logs innecesarios
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    volumes:
      # Esto evita que tus datos se borren al apagar el contenedor
      - mongodb_data:/data/db

volumes:
  mongodb_data: