services:
  app:
    build: .
    container_name: pdfextractext-app-1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://db:27017
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - db
      - ollama
    deploy:
      resources:
        limits:
          memory: 1G # La app de FastAPI no debería necesitar más

  db:
    image: mongo:latest
    container_name: pdfextractext-db-1
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 512M # MongoDB es ligero si no hay carga masiva

  ollama:
    image: ollama/ollama:latest
    container_name: pdfextractext-ai-1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=1        # No procesar varias peticiones a la vez
      - OLLAMA_MAX_LOADED_MODELS=1   # Solo un modelo en RAM
      - OLLAMA_KEEP_ALIVE=5m         # Liberar RAM si no se usa después de 5 min
    deploy:
      resources:
        limits:
          memory: 4.5G # El límite de seguridad para que no exploten tus 8GB totales

volumes:
  mongodb_data:
  ollama_data: